environment_module: "atropos.environments.gsm8k"

env:
  group_size: 8
  batch_size: 128
  batch_timeout: 60.0
  max_batches_offpolicy: 3
  tokenizer_name: "Qwen/Qwen2.5-3B"
  use_wandb: false
  rollout_server_url: "http://localhost:8000"
  wandb_name: "gsm8k-verl-atropos"
  ensure_scores_are_not_same: false
  max_token_length: 2048
  max_num_workers: 24
  total_steps: 5000
  steps_per_eval: 100

sync:
  min_steps_between_sync: 2
  max_steps_between_sync: 4
  queue_threshold: 2

openai:
  - model_name: "Qwen/Qwen2.5-3B"
    base_url: "http://localhost:8001/v1"
    api_key: "x"
    weight: 1.0
    num_requests_for_eval: 256

slurm: false
testing: false
